-- Создание свежей таблицы со всеми данными (имя_фамилияпациента_Raw). Это заготовка 1-го уровня.
create table raw.JackDoeRaw
(
	"Index" TEXT,
	"Date" TEXT,
	"Time" TEXT,
	"New Device Time" TEXT,
	"BG Reading (mmol/L)" TEXT,
	"Linked BG Meter ID" TEXT,
	"Basal Rate (U/h)" TEXT,
	"Temp Basal Amount" TEXT,
	"Temp Basal Type" TEXT,
	"Temp Basal Duration (h:mm:ss)" TEXT,
	"Bolus Type" TEXT,
	"Bolus Volume Selected (U)" TEXT,
	"Bolus Volume Delivered (U)" TEXT,
	"Bolus Duration (h:mm:ss)" TEXT,
	"Prime Type" TEXT,
	"Prime Volume Delivered (U)" TEXT,
	"Alarm" TEXT,
	"Suspend" TEXT,
	"Rewind" TEXT,
	"BWZ Estimate (U)" TEXT,
	"BWZ Target High BG (mmol/L)" TEXT,
	"BWZ Target Low BG (mmol/L)" TEXT,
	"BWZ Carb Ratio (U/Ex)" TEXT,
	"BWZ Insulin Sensitivity (mmol/L/U)" TEXT,
	"BWZ Carb Input (exchanges)" TEXT,
	"BWZ BG Input (mmol/L)" TEXT,
	"BWZ Correction Estimate (U)" TEXT,
	"BWZ Food Estimate (U)" TEXT,
	"BWZ Active Insulin (U)" TEXT,
	"BWZ Status" TEXT,
	"Sensor Calibration BG (mmol/L)" TEXT,
	"Sensor Glucose (mmol/L)" TEXT,
	"ISIG Value" TEXT,
	"Event Marker" TEXT,
	"Bolus Number" text,
	"Bolus Cancellation Reason" TEXT,
	"BWZ Unabsorbed Insulin Total (U)" text,
	"Final Bolus Estimate" TEXT,
	"Scroll Step Size" TEXT,
	"Insulin Action Curve Time" TEXT,
	"Sensor Calibration Rejected Reason" TEXT,
	"Preset Bolus" TEXT,
	"Bolus Source" TEXT,
	"BLE Network Device" TEXT,
	"Device Update Event" TEXT,
	"Network Device Associated Reason" TEXT,
	"Network Device Disassociated Reason" TEXT,
	"Network Device Disconnected Reason" TEXT,
	"Sensor Exception" TEXT,
	"Preset Temp Basal Name" TEXT
);

-- Создаём такую же таблицу, но добавляем ещё одну колонку с датой и временем загрузки.
create table raw.raw_data
(
	"Index" TEXT,
	"Date" TEXT,
	"Time" TEXT,
	"New Device Time" TEXT,
	"BG Reading (mmol/L)" TEXT,
	"Linked BG Meter ID" TEXT,
	"Basal Rate (U/h)" TEXT,
	"Temp Basal Amount" TEXT,
	"Temp Basal Type" TEXT,
	"Temp Basal Duration (h:mm:ss)" TEXT,
	"Bolus Type" TEXT,
	"Bolus Volume Selected (U)" TEXT,
	"Bolus Volume Delivered (U)" TEXT,
	"Bolus Duration (h:mm:ss)" TEXT,
	"Prime Type" TEXT,
	"Prime Volume Delivered (U)" TEXT,
	"Alarm" TEXT,
	"Suspend" TEXT,
	"Rewind" TEXT,
	"BWZ Estimate (U)" TEXT,
	"BWZ Target High BG (mmol/L)" TEXT,
	"BWZ Target Low BG (mmol/L)" TEXT,
	"BWZ Carb Ratio (U/Ex)" TEXT,
	"BWZ Insulin Sensitivity (mmol/L/U)" TEXT,
	"BWZ Carb Input (exchanges)" TEXT,
	"BWZ BG Input (mmol/L)" TEXT,
	"BWZ Correction Estimate (U)" TEXT,
	"BWZ Food Estimate (U)" TEXT,
	"BWZ Active Insulin (U)" TEXT,
	"BWZ Status" TEXT,
	"Sensor Calibration BG (mmol/L)" TEXT,
	"Sensor Glucose (mmol/L)" TEXT,
	"ISIG Value" TEXT,
	"Event Marker" TEXT,
	"Bolus Number" text,
	"Bolus Cancellation Reason" TEXT,
	"BWZ Unabsorbed Insulin Total (U)" text,
	"Final Bolus Estimate" TEXT,
	"Scroll Step Size" TEXT,
	"Insulin Action Curve Time" TEXT,
	"Sensor Calibration Rejected Reason" TEXT,
	"Preset Bolus" TEXT,
	"Bolus Source" TEXT,
	"BLE Network Device" TEXT,
	"Device Update Event" TEXT,
	"Network Device Associated Reason" TEXT,
	"Network Device Disassociated Reason" TEXT,
	"Network Device Disconnected Reason" TEXT,
	"Sensor Exception" TEXT,
	"Preset Temp Basal Name" TEXT,
	"LoadDateTime" timestamp default now()
);

--Теперь запускаем файл loading.bat. Он заполнит первую таблицу из .csv, скопирует данные во второую, во второй появится колонка со временем загрузки, первая таблица очистится.

--Увидеть дубли в исходнике (просто посмотреть, удаление другим способом ниже)
select "Date",
       "Time",
       "New Device Time",
       "BG Reading (mmol/L)",
       "Linked BG Meter ID",
       "Basal Rate (U/h)",
       "Temp Basal Amount",
       "Temp Basal Type",
       "Temp Basal Duration (h:mm:ss)",
       "Bolus Type",
       "Bolus Volume Selected (U)",
       "Bolus Volume Delivered (U)",
       "Bolus Duration (h:mm:ss)",
       "Prime Type",
       "Prime Volume Delivered (U)",
       "Alarm",
       "Suspend",
       "Rewind",
       "BWZ Estimate (U)",
       "BWZ Target High BG (mmol/L)",
       "BWZ Target Low BG (mmol/L)",
       "BWZ Carb Ratio (U/Ex)",
       "BWZ Insulin Sensitivity (mmol/L/U)",
       "BWZ Carb Input (exchanges)",
       "BWZ BG Input (mmol/L)",
       "BWZ Correction Estimate (U)",
       "BWZ Food Estimate (U)",
       "BWZ Active Insulin (U)",
       "BWZ Status",
       "Sensor Calibration BG (mmol/L)",
       "Sensor Glucose (mmol/L)",
       "ISIG Value",
       "Event Marker",
       "Bolus Number",
       "Bolus Cancellation Reason",
       "BWZ Unabsorbed Insulin Total (U)",
       "Final Bolus Estimate",
       "Scroll Step Size",
       "Insulin Action Curve Time",
       "Sensor Calibration Rejected Reason",
       "Preset Bolus",
       "Bolus Source",
       "BLE Network Device",
       "Device Update Event",
       "Network Device Associated Reason",
       "Network Device Disassociated Reason",
       "Network Device Disconnected Reason",
       "Sensor Exception",
       "Preset Temp Basal Name"
from raw.raw_data
group by "Date",
       "Time",
       "New Device Time",
       "BG Reading (mmol/L)",
       "Linked BG Meter ID",
       "Basal Rate (U/h)",
       "Temp Basal Amount",
       "Temp Basal Type",
       "Temp Basal Duration (h:mm:ss)",
       "Bolus Type",
       "Bolus Volume Selected (U)",
       "Bolus Volume Delivered (U)",
       "Bolus Duration (h:mm:ss)",
       "Prime Type",
       "Prime Volume Delivered (U)",
       "Alarm",
       "Suspend",
       "Rewind",
       "BWZ Estimate (U)",
       "BWZ Target High BG (mmol/L)",
       "BWZ Target Low BG (mmol/L)",
       "BWZ Carb Ratio (U/Ex)",
       "BWZ Insulin Sensitivity (mmol/L/U)",
       "BWZ Carb Input (exchanges)",
       "BWZ BG Input (mmol/L)",
       "BWZ Correction Estimate (U)",
       "BWZ Food Estimate (U)",
       "BWZ Active Insulin (U)",
       "BWZ Status",
       "Sensor Calibration BG (mmol/L)",
       "Sensor Glucose (mmol/L)",
       "ISIG Value",
       "Event Marker",
       "Bolus Number",
       "Bolus Cancellation Reason",
       "BWZ Unabsorbed Insulin Total (U)",
       "Final Bolus Estimate",
       "Scroll Step Size",
       "Insulin Action Curve Time",
       "Sensor Calibration Rejected Reason",
       "Preset Bolus",
       "Bolus Source",
       "BLE Network Device",
       "Device Update Event",
       "Network Device Associated Reason",
       "Network Device Disassociated Reason",
       "Network Device Disconnected Reason",
       "Sensor Exception",
       "Preset Temp Basal Name"
having count(*)>1
order by "Date", "Time";

--Удаление дублей с нумерацией и ctid
delete from raw.raw_data
where CTID in (
select CTID from
(select
        CTID,
        row_number() over (partition by "Date",
       "Time",
       "New Device Time",
       "BG Reading (mmol/L)",
       "Linked BG Meter ID",
       "Basal Rate (U/h)",
       "Temp Basal Amount",
       "Temp Basal Type",
       "Temp Basal Duration (h:mm:ss)",
       "Bolus Type",
       "Bolus Volume Selected (U)",
       "Bolus Volume Delivered (U)",
       "Bolus Duration (h:mm:ss)",
       "Prime Type",
       "Prime Volume Delivered (U)",
       "Alarm",
       "Suspend",
       "Rewind",
       "BWZ Estimate (U)",
       "BWZ Target High BG (mmol/L)",
       "BWZ Target Low BG (mmol/L)",
       "BWZ Carb Ratio (U/Ex)",
       "BWZ Insulin Sensitivity (mmol/L/U)",
       "BWZ Carb Input (exchanges)",
       "BWZ BG Input (mmol/L)",
       "BWZ Correction Estimate (U)",
       "BWZ Food Estimate (U)",
       "BWZ Active Insulin (U)",
       "BWZ Status",
       "Sensor Calibration BG (mmol/L)",
       "Sensor Glucose (mmol/L)",
       "ISIG Value",
       "Event Marker",
       "Bolus Number",
       "Bolus Cancellation Reason",
       "BWZ Unabsorbed Insulin Total (U)",
       "Final Bolus Estimate",
       "Scroll Step Size",
       "Insulin Action Curve Time",
       "Sensor Calibration Rejected Reason",
       "Preset Bolus",
       "Bolus Source",
       "BLE Network Device",
       "Device Update Event",
       "Network Device Associated Reason",
       "Network Device Disassociated Reason",
       "Network Device Disconnected Reason",
       "Sensor Exception",
       "Preset Temp Basal Name"
   order by "Date", "Time") as Num, "Date",
       "Time",
       "New Device Time",
       "BG Reading (mmol/L)",
       "Linked BG Meter ID",
       "Basal Rate (U/h)",
       "Temp Basal Amount",
       "Temp Basal Type",
       "Temp Basal Duration (h:mm:ss)",
       "Bolus Type",
       "Bolus Volume Selected (U)",
       "Bolus Volume Delivered (U)",
       "Bolus Duration (h:mm:ss)",
       "Prime Type",
       "Prime Volume Delivered (U)",
       "Alarm",
       "Suspend",
       "Rewind",
       "BWZ Estimate (U)",
       "BWZ Target High BG (mmol/L)",
       "BWZ Target Low BG (mmol/L)",
       "BWZ Carb Ratio (U/Ex)",
       "BWZ Insulin Sensitivity (mmol/L/U)",
       "BWZ Carb Input (exchanges)",
       "BWZ BG Input (mmol/L)",
       "BWZ Correction Estimate (U)",
       "BWZ Food Estimate (U)",
       "BWZ Active Insulin (U)",
       "BWZ Status",
       "Sensor Calibration BG (mmol/L)",
       "Sensor Glucose (mmol/L)",
       "ISIG Value",
       "Event Marker",
       "Bolus Number",
       "Bolus Cancellation Reason",
       "BWZ Unabsorbed Insulin Total (U)",
       "Final Bolus Estimate",
       "Scroll Step Size",
       "Insulin Action Curve Time",
       "Sensor Calibration Rejected Reason",
       "Preset Bolus",
       "Bolus Source",
       "BLE Network Device",
       "Device Update Event",
       "Network Device Associated Reason",
       "Network Device Disassociated Reason",
       "Network Device Disconnected Reason",
       "Sensor Exception",
       "Preset Temp Basal Name"
    from raw.raw_data
    ) as Dubl
where Dubl.Num>1);

--Проверка дат в raw (удобно, чтобы помотреть период, за который есть данные в таблице)
select max("Date"::date), min("Date"::date)
from raw.raw_data
where replace("Sensor Glucose (mmol/L)",',','.')::numeric(3,1) is not null;

--Посчитать записи на каждую дату
select "Date"::date, count(*)
from raw.raw_data
group by "Date"
ORDER BY "Date"::date;