-- Создание свежей таблицы со всеми данными (имя_фамилияпациента_Raw). Это заготовка 1-го уровня.
create table raw.JackDoeRaw
(
	"Index" TEXT,
	"Date" TEXT,
	"Time" TEXT,
	"New Device Time" TEXT,
	"BG Reading (mmol/L)" TEXT,
	"Linked BG Meter ID" TEXT,
	"Basal Rate (U/h)" TEXT,
	"Temp Basal Amount" TEXT,
	"Temp Basal Type" TEXT,
	"Temp Basal Duration (h:mm:ss)" TEXT,
	"Bolus Type" TEXT,
	"Bolus Volume Selected (U)" TEXT,
	"Bolus Volume Delivered (U)" TEXT,
	"Bolus Duration (h:mm:ss)" TEXT,
	"Prime Type" TEXT,
	"Prime Volume Delivered (U)" TEXT,
	"Alarm" TEXT,
	"Suspend" TEXT,
	"Rewind" TEXT,
	"BWZ Estimate (U)" TEXT,
	"BWZ Target High BG (mmol/L)" TEXT,
	"BWZ Target Low BG (mmol/L)" TEXT,
	"BWZ Carb Ratio (U/Ex)" TEXT,
	"BWZ Insulin Sensitivity (mmol/L/U)" TEXT,
	"BWZ Carb Input (exchanges)" TEXT,
	"BWZ BG Input (mmol/L)" TEXT,
	"BWZ Correction Estimate (U)" TEXT,
	"BWZ Food Estimate (U)" TEXT,
	"BWZ Active Insulin (U)" TEXT,
	"BWZ Status" TEXT,
	"Sensor Calibration BG (mmol/L)" TEXT,
	"Sensor Glucose (mmol/L)" TEXT,
	"ISIG Value" TEXT,
	"Event Marker" TEXT,
	"Bolus Number" text,
	"Bolus Cancellation Reason" TEXT,
	"BWZ Unabsorbed Insulin Total (U)" text,
	"Final Bolus Estimate" TEXT,
	"Scroll Step Size" TEXT,
	"Insulin Action Curve Time" TEXT,
	"Sensor Calibration Rejected Reason" TEXT,
	"Preset Bolus" TEXT,
	"Bolus Source" TEXT,
	"BLE Network Device" TEXT,
	"Device Update Event" TEXT,
	"Network Device Associated Reason" TEXT,
	"Network Device Disassociated Reason" TEXT,
	"Network Device Disconnected Reason" TEXT,
	"Sensor Exception" TEXT,
	"Preset Temp Basal Name" TEXT
);

-- Создаём такую же таблицу, но добавляем ещё одну колонку с датой и временем загрузки.
create table raw.raw_data
(
	"Index" TEXT,
	"Date" TEXT,
	"Time" TEXT,
	"New Device Time" TEXT,
	"BG Reading (mmol/L)" TEXT,
	"Linked BG Meter ID" TEXT,
	"Basal Rate (U/h)" TEXT,
	"Temp Basal Amount" TEXT,
	"Temp Basal Type" TEXT,
	"Temp Basal Duration (h:mm:ss)" TEXT,
	"Bolus Type" TEXT,
	"Bolus Volume Selected (U)" TEXT,
	"Bolus Volume Delivered (U)" TEXT,
	"Bolus Duration (h:mm:ss)" TEXT,
	"Prime Type" TEXT,
	"Prime Volume Delivered (U)" TEXT,
	"Alarm" TEXT,
	"Suspend" TEXT,
	"Rewind" TEXT,
	"BWZ Estimate (U)" TEXT,
	"BWZ Target High BG (mmol/L)" TEXT,
	"BWZ Target Low BG (mmol/L)" TEXT,
	"BWZ Carb Ratio (U/Ex)" TEXT,
	"BWZ Insulin Sensitivity (mmol/L/U)" TEXT,
	"BWZ Carb Input (exchanges)" TEXT,
	"BWZ BG Input (mmol/L)" TEXT,
	"BWZ Correction Estimate (U)" TEXT,
	"BWZ Food Estimate (U)" TEXT,
	"BWZ Active Insulin (U)" TEXT,
	"BWZ Status" TEXT,
	"Sensor Calibration BG (mmol/L)" TEXT,
	"Sensor Glucose (mmol/L)" TEXT,
	"ISIG Value" TEXT,
	"Event Marker" TEXT,
	"Bolus Number" text,
	"Bolus Cancellation Reason" TEXT,
	"BWZ Unabsorbed Insulin Total (U)" text,
	"Final Bolus Estimate" TEXT,
	"Scroll Step Size" TEXT,
	"Insulin Action Curve Time" TEXT,
	"Sensor Calibration Rejected Reason" TEXT,
	"Preset Bolus" TEXT,
	"Bolus Source" TEXT,
	"BLE Network Device" TEXT,
	"Device Update Event" TEXT,
	"Network Device Associated Reason" TEXT,
	"Network Device Disassociated Reason" TEXT,
	"Network Device Disconnected Reason" TEXT,
	"Sensor Exception" TEXT,
	"Preset Temp Basal Name" TEXT,
	"LoadDateTime" timestamp default now()
);

--Теперь запускаем файл